### ISSUE TITLE
Category (Drop Down List)

### ISSUE THREAD

**Issue by profoundhub** [profoundhub/CoderSites#5]
Change the "Description" column to a drop down list. 
- Tribute Page
- Personal Portfolio Webpage
- Random Quote Machine
- Show the Local Weather
- Wikipedia Viewer 
- Twitch.tv JSON API
- JavaScript Calculator
- Pomodoro Clock
- Tic Tac Toe Game 
- Simon Says Game
- Build a Markdown Previewer
- Build a Camper Leaderboard
- Build a Recipe Box
- Build the Game of Life
- Build a Roguelike Dungeon Crawler Game
- Visualize Data with a Bar Chart
- Visualize Data with a Scatterplot Graph
- Visualize Data with a Heat Map
- Show Relationships with a Force Directed Graph
- Map Data Across the Globe
- Timestamp Microservice
- Request Header Parser Microservice
- URL Shortener Microservice
- Image Search Abstraction Layer
- File Metadata Microservice
- Build a Voting App
- Build a Nightlife Coordination App
- Chart the Stock Market
- Manage a Book Trading Club
- Build a Pinterest Clone
- Others

**Comment by PJonestown** [comment]
So you want the word 'incomplete' in some of the names?

eg. "Use the Twitch.tv JSON API Incomplete"

**Comment by PJonestown** [comment]
Or do you mean the name is incomplete and needs more work?

**Comment by profoundhub** [comment]
Sorry for the confusion, I've removed the word "Incomplete" and typed the exact phrases instead.
