### ISSUE TITLE
Change body column to description in Posts table

### ISSUE THREAD

**Issue by PJonestown** [profoundhub/CoderSites#6]
There's no body column in the form and in your posts/show view you label label the body as description.

Makes sense just to change the name to description. It's more descriptive and a more accurate name.

I can do this in my pull request for the description issue I'm already working on

**Comment by profoundhub** [comment]
I tried changing it to Description but was having problems with it. either way, we need to change that column to a drop down list of the Projects. 

I've compiled the list, you can find it here: https://github.com/profoundhub/CoderSites/issues/5
